# Generated by Django 5.2 on 2025-07-13 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedCombination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generated_date", models.DateTimeField(auto_now_add=True)),
                ("main_numbers", models.CharField(max_length=100)),
                ("mega_ball", models.IntegerField()),
                (
                    "game_type",
                    models.CharField(
                        choices=[
                            ("mega_millions", "Mega Millions"),
                            ("powerball", "Powerball"),
                        ],
                        default="mega_millions",
                        max_length=20,
                    ),
                ),
                (
                    "generation_method",
                    models.CharField(default="random", max_length=50),
                ),
                ("seed_number", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="LotteryDraw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game_type",
                    models.CharField(
                        choices=[
                            ("mega_millions", "Mega Millions"),
                            ("powerball", "Powerball"),
                        ],
                        default="mega_millions",
                        max_length=20,
                    ),
                ),
                ("draw_date", models.DateTimeField()),
                ("winning_numbers", models.CharField(max_length=100)),
                ("mega_ball", models.IntegerField()),
                ("megaplier", models.IntegerField(blank=True, null=True)),
                (
                    "estimated_jackpot",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "jackpot_winners",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("export_date", models.DateTimeField(auto_now_add=True)),
                (
                    "export_type",
                    models.CharField(
                        choices=[("csv", "CSV"), ("excel", "Excel")], max_length=20
                    ),
                ),
                ("file_name", models.CharField(max_length=200)),
                (
                    "game_type",
                    models.CharField(
                        choices=[
                            ("mega_millions", "Mega Millions"),
                            ("powerball", "Powerball"),
                        ],
                        max_length=20,
                    ),
                ),
                ("combinations_count", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SavedCombination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "combination_name",
                    models.CharField(default="My Numbers", max_length=100),
                ),
                ("main_numbers", models.CharField(max_length=100)),
                ("mega_ball", models.IntegerField()),
                (
                    "game_type",
                    models.CharField(
                        choices=[
                            ("mega_millions", "Mega Millions"),
                            ("powerball", "Powerball"),
                        ],
                        default="mega_millions",
                        max_length=20,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("is_favorite", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CombinationCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matches_main", models.IntegerField(default=0)),
                ("matches_mega", models.BooleanField(default=False)),
                ("check_date", models.DateTimeField(auto_now_add=True)),
                ("prize_tier", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "estimated_winnings",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "draw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="generator.lotterydraw",
                    ),
                ),
                (
                    "saved_combination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="generator.savedcombination",
                    ),
                ),
            ],
            options={
                "unique_together": {("saved_combination", "draw")},
            },
        ),
    ]
