# Generated by Django 5.2 on 2025-04-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneratedCombination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generated_date", models.DateTimeField(auto_now_add=True)),
                ("main_numbers", models.CharField(max_length=100)),
                ("mega_ball", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="LotteryDraw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("draw_date", models.DateTimeField()),
                ("winning_numbers", models.CharField(max_length=100)),
                ("mega_ball", models.IntegerField()),
                ("megaplier", models.IntegerField(blank=True, null=True)),
                (
                    "estimated_jackpot",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "jackpot_winners",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
    ]
